### ISSUE TITLE
config.sample.json is missing

### ISSUE THREAD

**Issue by lokiuox** [MarkusBauer/saarctf-gameserver#1]
The documentation says there should be a `config.sample.json` file, but it's missing and the setup cannot be completed without it.

**Comment by MarkusBauer** [comment]
I'm sorry, I just added the sample configuration: [https://github.com/MarkusBauer/saarctf-gameserver/blob/master/config.sample.json](https://github.com/MarkusBauer/saarctf-gameserver/blob/master/config.sample.json).
